### PR TITLE
Changed Backend Model Image by variable

### PR DESCRIPTION
**Pull request by osrecio**
Changed `Staempfli\StoreLocator\Model\Locations` by variable to stop and Change by desired Model

### CODE REVIEW

**Comment by jalogut** [comment]
Hi @osrecio thanks for your PR. What about adding 2 variables instead of on like that?

`$vendor$\$package$\Model\Attribute\Backend\Image`

What do you think?

**Comment by osrecio** [comment]
Sounds good!

I think is better than only set model.

Thanks for you efforts with awesome tool!

**Comment by jalogut** [comment]
Hi @osrecio, could you also add "Model" after the variables:

`$vendor$\$package$\Model\Attribute\Backend\Image`

After that, I will accept the pull request and also upload a new .jar file with the changes.

Thanks

**Comment by osrecio** [comment]
Sorry, this happens to edit directly in github.com.

Solved!

**Pull request merged**
